language: ruby
rvm:
- 2.4.0
sudo: required
os:
- linux
- osx
addons:
  artifacts:
    paths:
    - ./pkg
    target_paths:
    - /3scale/3scale_toolbox/omnibus/$TRAVIS_OS_NAME/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}
cache: bundler
before_script:
- "rm -rf pkg/*"
script:
- "./build.sh"
