language: ruby
sudo: required
# skip installation step
install: true
matrix:
  include:
    - os: osx
      env:
        - BUILD_ENGINE=native
      rvm: 2.4.0
    - os: linux
      env:
        - BUILD_ENGINE=docker
        - DOCKER_TAG=xenial-2.4.1
      services:
        - docker
    - os: linux
      env:
        - BUILD_ENGINE=docker
        - DOCKER_TAG=centos7-2.4
      services:
        - docker
addons:
  artifacts:
    paths:
    - ./pkg
    target_paths:
    - /3scale/3scale_toolbox/omnibus/$TRAVIS_OS_NAME/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}

before_script:
- "rm -rf pkg/*"
script:
- "./${BUILD_ENGINE}.sh"
- "ls -lah pkg"
